apiVersion: v1
kind: LimitRange
metadata:
  name: limit-jupyter-container
spec:
  limits:
  - max:
      cpu: 2
      memory: 4096Mi
    default:
      cpu: 1.5
      memory: 2048Mi
    defaultRequest:
      cpu: 0.5
      memory: 500Mi 
    type: Container